# Generated by Django 6.0.4 on 2026-07-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='scheduledDate',
            new_name='scheduled_date',
        ),
    ]
