# Generated by Django 6.0.4 on 2026-07-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTracker', '0002_rename_scheduleddate_task_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
    ]
