# Generated by Django 6.0.4 on 2026-07-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTracker', '0004_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
