# Generated by Django 6.0.4 on 2026-07-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTracker', '0006_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
