# Generated by Django 6.0.4 on 2026-07-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTracker', '0009_checkinevaluation_distractionsevaluation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinevaluation',
            name='focusing',
        ),
        migrations.RemoveField(
            model_name='checkinevaluation',
            name='not_focusing',
        ),
        migrations.RemoveField(
            model_name='checkinevaluation',
            name='sort_of_focusing',
        ),
        migrations.AddField(
            model_name='checkinevaluation',
            name='focusing_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distractionsevaluation',
            name='eating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distractionsevaluation',
            name='phone',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distractionsevaluation',
            name='starting_other_tasks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='distractionsevaluation',
            name='zoning_out',
            field=models.FloatField(default=0),
        ),
    ]
